;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2019/6/21 8:39:56

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=1.快键说明.txt	; 快键说明
IDH_1001=2.皮肤说明.txt	; 皮肤说明
IDH_1002=3.关卡文档格式.txt	; 关卡文档格式
