;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2019/6/21 8:39:56

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; 快键说明 1.快键说明.txt
#define IDH_1001	1001	; 皮肤说明 2.皮肤说明.txt
#define IDH_1002	1002	; 关卡文档格式 3.关卡文档格式.txt
